group_imports = "StdExternalCrate"  # Group standard imports, external crates, and local imports separately
reorder_imports = true              # Arrange imports alphabetically
imports_granularity = "Module"      # Merge imports from the same module into one
max_width = 100                     # Set maximum line width to 100 characters